# Generated by Django 4.2 on 2026-04-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='kopmas_addresses',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='kopmas_carts',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='kopmas_cart_items',
        ),
        migrations.AlterModelTable(
            name='category',
            table='kopmas_categories',
        ),
        migrations.AlterModelTable(
            name='emailotp',
            table='kopmas_email_otps',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='kopmas_notifications',
        ),
        migrations.AlterModelTable(
            name='order',
            table='kopmas_orders',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='kopmas_order_items',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='kopmas_payments',
        ),
        migrations.AlterModelTable(
            name='product',
            table='kopmas_products',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='kopmas_product_images',
        ),
        migrations.AlterModelTable(
            name='productreview',
            table='kopmas_product_review',
        ),
        migrations.AlterModelTable(
            name='productvariation',
            table='kopmas_product_variations',
        ),
        migrations.AlterModelTable(
            name='role',
            table='kopmas_roles',
        ),
        migrations.AlterModelTable(
            name='sellerbankaccount',
            table='kopmas_seller_bank_accounts',
        ),
        migrations.AlterModelTable(
            name='sellerpaymentmethodsetting',
            table='kopmas_seller_payment_method_settings',
        ),
        migrations.AlterModelTable(
            name='store',
            table='kopmas_stores',
        ),
        migrations.AlterModelTable(
            name='user',
            table='kopmas_users',
        ),
        migrations.AlterModelTable(
            name='variantoption',
            table='kopmas_variant_options',
        ),
    ]
