# Generated by Django 5.0.14 on 2026-03-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel_admin", "0002_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tagline",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
