# Generated by Django 5.0.14 on 2026-04-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel_admin", "0011_alter_product_discount_price_alter_product_price"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE products DROP COLUMN IF EXISTS sku;",
                    reverse_sql="ALTER TABLE products ADD COLUMN IF NOT EXISTS sku varchar(50);",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE products DROP COLUMN IF EXISTS stock;",
                    reverse_sql="ALTER TABLE products ADD COLUMN IF NOT EXISTS stock integer NOT NULL DEFAULT 0;",
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="product",
                    name="sku",
                ),
                migrations.RemoveField(
                    model_name="product",
                    name="stock",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                decimal_places=0, default=0, help_text="Weight in grams", max_digits=8
            ),
        ),
    ]
