# Generated by Django 5.0.14 on 2026-04-06 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel_admin", "0012_remove_product_sku_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE product_variations DROP COLUMN IF EXISTS created_at;",
                    reverse_sql="ALTER TABLE product_variations ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;",
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="productvariation",
                    name="created_at",
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariantOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_name", models.CharField(max_length=80)),
                ("option_value", models.CharField(max_length=120)),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_options",
                        to="panel_admin.productvariation",
                    ),
                ),
            ],
            options={
                "db_table": "variant_options",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="variantoption",
            constraint=models.UniqueConstraint(
                fields=("variation", "option_name", "option_value"),
                name="unique_variation_option_pair",
            ),
        ),
    ]
