# Generated by Django 5.0.14 on 2026-04-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel_admin", "0017_productreview_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon_key",
            field=models.CharField(
                choices=[
                    ("food", "Makanan"),
                    ("drink", "Minuman"),
                    ("craft", "Craft"),
                    ("fashion", "Fashion"),
                    ("agriculture", "Pertanian"),
                    ("service", "Jasa"),
                    ("electronics", "Elektronik"),
                    ("beauty", "Kecantikan"),
                    ("books", "Buku"),
                    ("toys", "Mainan"),
                    ("sports", "Olahraga"),
                    ("health", "Kesehatan"),
                    ("pet", "Hewan Peliharaan"),
                    ("automotive", "Otomotif"),
                    ("home", "Rumah Tangga"),
                    ("office", "Perlengkapan Kantor"),
                    ("travel", "Travel"),
                    ("music", "Musik"),
                    ("gift", "Hadiah"),
                    ("baby", "Bayi & Anak"),
                ],
                default="food",
                max_length=20,
            ),
        ),
    ]
