# Generated by Django 5.0.14 on 2026-04-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel_admin", "0022_store_supplier_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
