# Generated by Django 5.0.14 on 2026-04-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("panel_admin", "0023_alter_category_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["created_at"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
