# Generated by Django 5.0.14 on 2026-04-15 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("panel_admin", "0024_alter_category_options_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="logo",
        ),
    ]
