# Generated by Django 5.0.14 on 2026-04-15 03:32

from django.db import migrations, models


def backfill_store_address_components(apps, schema_editor):
    Address = apps.get_model("panel_admin", "Address")
    legacy_prefix = "DI Yogyakarta, Sleman ("
    update_fields = ["province", "city", "sub_district", "village"]

    for address in Address.objects.filter(label="Alamat Toko"):
        province = (address.province or "").strip()
        legacy_city = (address.city or "").strip()
        changed = False

        if province.startswith(legacy_prefix) and province.endswith(")"):
            district_name = province[len(legacy_prefix) : -1].strip()

            if district_name and not (address.sub_district or "").strip():
                address.sub_district = district_name
                changed = True

            if legacy_city and legacy_city != "Sleman" and not (address.village or "").strip():
                address.village = legacy_city
                changed = True

            if province != "DI Yogyakarta":
                address.province = "DI Yogyakarta"
                changed = True

            if legacy_city != "Sleman":
                address.city = "Sleman"
                changed = True

        if changed:
            address.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("panel_admin", "0025_remove_store_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="sub_district",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="village",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RunPython(backfill_store_address_components, noop_reverse),
    ]
